apiVersion: v1
kind: Secret
metadata:
  name: consul-token
type: Opaque
data:
  consul-token: {{ randAlphaNum 24 | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: vault-tls
type: Opaque
data:
  key:
  cert:
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Component}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
    - name: vaultport
      port: {{.Values.VaultPort}}
      protocol: TCP
  selector:
    component: "{{.Release.Name}}-{{.Values.Component}}"
---
#apiVersion: extensions/v1beta1
#kind: Ingress
#metadata:
#  name: vault
#  namespace: kube-system
#  labels:
#    ssl: "true"
#spec:
#  rules:
#  - host: ###vault%%ENVIRONMENT%%.somedomain.com###
#    http:
#      paths:
#      - backend:
#          serviceName: vault
#          servicePort: ###SOME_HIGH_PORT_HTTPS###
#        path: /
#---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Name}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  replicas: {{default 1 .Values.Replicas | quote }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{.Release.Name}}-{{.Values.Component}}"
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-{{.Values.Component}}"
    spec:
      containers:
        - name: "{{ printf "%s-%s" .Release.Name .Values.Name | trunc 24 }}"
          image: "{{.Values.Image}}:{{.Values.ImageTag}}"
          imagePullPolicy: "{{.Values.ImagePullPolicy}}"
          env:
            - name: CONSUL_SERVICE_HOST
              value: "{{ .Values.ConsulServiceHost }}"
            - name: CONSUL_SERVICE_PORT
              value: "{{ .Values.ConsulServicePort }}"
            - name: CONSUL_TOKEN
              valueFrom:
                secretKeyRef:
                  name: consul-token
                  key: consul-token
            - name: "VAULT_DEBUG"
              value: "true"
            - name: "VAULT_SSL_KEY"
              valueFrom:
                secretKeyRef:
                  name: vault-tls
                  key: key
            - name: "VAULT_SSL_CRT"
              valueFrom:
                secretKeyRef:
                  name: vault-tls
                  key: cert
          ports:
            - containerPort: {{.Values.VaultPort}}
          resources:
            requests:
              cpu: "{{.Values.Cpu}}"
        #  readinessProbe:
        #    httpGet:
        #      path: /v1/sys/health
        #      port: {{.Values.VaultPort}}
        #    initialDelaySeconds: 10
        #    timeoutSeconds: 1
