# Default values for spark.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
# name: value

Master:
  Name: spark-master
  Image: "gcr.io/google_containers/spark"
  Image_tag: "1.5.1_v3"
  Replicas: 1
  Component: "spark-master"
  Cpu: "100m"
  ServicePort: 7077
  ContainerPort: 7077

WebUi:
  Name: spark-webui
  ServicePort: 8080
  ContainerPort: 8080

Worker:
  Name: spark-worker
  Image: "gcr.io/google_containers/spark"
  Image_tag: "1.5.1_v3"
  Replicas: 3
  Component: "spark-worker"
  Cpu: "100m"
  ContainerPort: 8081

Zeppelin:
  Name: zeppelin-controller
  Image: "gcr.io/google_containers/zeppelin"
  Image_tag: "v0.5.5_v2"
  Replicas: 1
  Component: "zeppelin"
  Cpu: "100m"
  ServicePort: 8080
  ContainerPort: 8080
