apiVersion: v1
kind: Service
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Master.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  ports:
    - port: {{.Values.Master.ServicePort}}
      targetPort: {{.Values.Master.ContainerPort}}
  selector:
    component: "{{.Release.Name}}-{{.Values.Master.Component}}"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{ printf "%s-%s" .Release.Name .Values.Master.Name | trunc 24 }}"
  labels:
    heritage: {{.Release.Service | quote }}
    release: {{.Release.Name | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    component: "{{.Release.Name}}-{{.Values.Master.Name}}"
  annotations:
    "helm.sh/created": {{.Release.Time.Seconds | quote }}
spec:
  replicas: {{default 1 .Values.Master.Replicas | quote }}
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      component: "{{.Release.Name}}-{{.Values.Master.Component}}"
  template:
    metadata:
      labels:
        heritage: {{.Release.Service | quote }}
        release: {{.Release.Name | quote }}
        chart: "{{.Chart.Name}}-{{.Chart.Version}}"
        component: "{{.Release.Name}}-{{.Values.Master.Component}}"
    spec:
      containers:
        - name: "{{ printf "%s-%s" .Release.Name .Values.Master.Name | trunc 24 }}"
          image: "{{.Values.Master.Image}}:{{.Values.Master.ImageTag}}"
          #command: ["/bin/sh","-c"]
          ports:
            - containerPort: {{.Values.Master.ContainerPort}}
            - containerPort: {{.Values.WebUi.ContainerPort}}
          resources:
            requests:
              cpu: "{{.Values.Master.Cpu}}"
